const mysql = require('mysql2/promise');

const dbConfig = {
    host: 'localhost',
    user: 'admin_web',
    password: '101104',
    database: 'greenfields_mvp'
};

const scenarios = {
    INFO: [
        { judul: "Pengecekan Rutin Mesin A", deskripsi: "Suhu mesin stabil di 45°C. Tidak ada anomali." },
        { judul: "Sinkronisasi Database Sukses", deskripsi: "Backup data harian ke cloud selesai dalam 12 detik." },
        { judul: "Kalibrasi Sensor Kelembapan", deskripsi: "Sensor di sektor B telah dikalibrasi ulang oleh tim shift pagi." }
    ],
    WARNING: [
        { judul: "Getaran Mesin B Melebihi Batas", deskripsi: "Sensor mendeteksi getaran 15% di atas batas normal. Perlu pelumasan." },
        { judul: "Kapasitas RAM Server Hampir Penuh", deskripsi: "Penggunaan memori mencapai 88%. Menunggu auto-scaling aktif." },
        { judul: "Tegangan Listrik Fluktuatif", deskripsi: "Terjadi penurunan tegangan sesaat di panel utama gedung produksi." }
    ],
    CRITICAL: [
        { judul: "🚨 Kebocoran Pipa Valve Utama", deskripsi: "Tekanan air menurun drastis! Terindikasi kebocoran parah pada ring valve C." },
        { judul: "🚨 Server Database Down!", deskripsi: "Koneksi ke master database terputus. Sistem beralih ke mode read-only." },
        { judul: "🚨 Overheat pada Motor Penggerak", deskripsi: "Suhu motor utama menembus 110°C. Sistem otomatis mematikan daya (Emergency Stop)." }
    ]
};

async function runSimulator() {
    console.log("=========================================");
    console.log("🤖 GREENFIELDS SENSOR SIMULATOR STARTED");
    console.log("=========================================\n");

    const connection = await mysql.createConnection(dbConfig);

    setInterval(async () => {
        try {
            const rand = Math.random();
            let level = 'INFO';
            if (rand > 0.4 && rand <= 0.75) level = 'WARNING';
            if (rand > 0.75) level = 'CRITICAL';

            const scenarioList = scenarios[level];
            const selected = scenarioList[Math.floor(Math.random() * scenarioList.length)];

            const [logResult] = await connection.execute(
                `INSERT INTO incident_logs (judul, deskripsi, severity_level, status) VALUES (?, ?, ?, ?)`,
                [selected.judul, selected.deskripsi, level, 'OPEN']
            );

            await connection.execute(
                `INSERT INTO audit_trails (incident_id, user_id, aksi, data_baru) VALUES (?, ?, ?, ?)`,
                [logResult.insertId, 99, 'CREATED', JSON.stringify({ message: 'Auto-generated by IoT Sensor' })]
            );

            const time = new Date().toLocaleTimeString('id-ID');
            if (level === 'CRITICAL') {
                console.log(`[${time}] 🔴 CRITICAL ALERT TRIGGERED: ${selected.judul}`);
            } else if (level === 'WARNING') {
                console.log(`[${time}] 🟡 WARNING LOGGED: ${selected.judul}`);
            } else {
                console.log(`[${time}] 🔵 INFO: ${selected.judul}`);
            }

        } catch (error) {
            console.error("Gagal mengirim data sensor:", error.message);
        }
    }, 5000); 
}

runSimulator().catch(err => console.error(err));